(defun unpack (lst)
  (labels ((rep (counter item)
				(let (acc)
				  (dotimes (i counter) (push item acc))
				  acc))
		   (rec (lst acc)
				(cond ((null lst) acc)
					  ((atom (car lst)) (rec (cdr lst) (cons (car lst) acc)))
					  (t (rec (cdr lst) (append (rep (caar lst) (cadar lst)) acc))))))
	(nreverse (rec lst '()))))
