#!/usr/bin/env python

import sys
import zipfile
import xml.dom.minidom
from xmlutil import getText

mydoc = zipfile.ZipFile(sys.argv[1])
document = mydoc.read('word/document.xml')
dom = xml.dom.minidom.parseString(document)
print(getText(dom))
