#!/usr/bin/env python

import zipfile
import xml.dom.minidom
from xmlutil import getText, getInput

mydoc = zipfile.ZipFile(getInput())
document = mydoc.read('word/document.xml')
dom = xml.dom.minidom.parseString(document)
print(getText(dom))
