#!/usr/bin/env python

# Watch for modified files in dir and react.
# ./Watch <cmd>
# If cmd ends with '-', then modified filename is appended to cmd
# i.e.: ./Watch flake8 .

# TODO
# write OK
# triggered too many times from acme
# kill itself

from pyinotify import WatchManager, EventsCodes, ProcessEvent, Notifier
from subprocess import call
import os
import sys


class ProcessManager(ProcessEvent):

    def __init__(self, cmds):
        super(ProcessEvent, self).__init__()
        self.cmds = cmds
    
#    def get_file_from_event(self, event):
#        return os.path.join(event.path, event.name)
#                
    def process_IN_CLOSE_WRITE(self, event):
        call(self.cmds)


def main():
    
    dir = '.'
    cmds = sys.argv[1:]
    
    wm = WatchManager()
    
    mask = EventsCodes.ALL_FLAGS['IN_CLOSE_WRITE']
    
    notifier = Notifier(wm, ProcessManager(cmds))
    wdd = wm.add_watch(dir, mask, rec=True)
    
    while True:
        try:
            notifier.process_events()
            if notifier.check_events():
                notifier.read_events()
        except KeyboardInterrupt:
            notifier.stop()
            break


if __name__ == '__main__':
    main()